### PR TITLE
multiLanguage option

### PR DESCRIPTION
**Pull request by fbarbare**
This option of `multiLanguage` makes it possible to group `namespaces` into a single request but having it per language.
It defaults to `true` to keep the package backwards compatible.

So say you want to make a request like this: `GET /translations/en/ns1+ns2+ns3` to only return data for 1 language and not mix up languages, you can.

No need for the language in the returned data either. So instead of:
```js
{
  en: {
    ns1: { ...keys }
  },
  de: {
    ns1: { ...keys }
  }
}
```
You would return data like so:
```js
{
  ns1: { ...keys },
  ns2: { ...keys },
  ns3: { ...keys }
}
```

### CODE REVIEW

**Comment by fbarbare** [comment]
I updated the README and the CHANGELOG

**Comment by fbarbare** [comment]
Hi @jamuhl 

The reason for that PR is that usually when getting translations, you don't want to get multiple languages at the same time: the page `should` be in 1 language only.. It'd be weird otherwise, but why not (maybe for showing/editing the translations, but the only use case I see).
So having an API to get data like this: `GET /translations?lng=en;de&ns=ns1;ns2;ns3` is not really "benefitting" the use of multiload for websites and forces you to create more complex API.

As you said, `the multiload option is used rarely`. And I think this is because it doesn't actually fit a website's translation system, which always shows only 1 language.
For me multiload should not be about multiple languages at the same time as the websites pages are only in 1 language, but about multiple namespaces at the same time, which actually brings the benefit of loading all your translations at once.
So data like so: `GET /translations/en?ns=ns1;ns2;ns3` is much more natural, and makes it easier to create your API endpoints.

Let me know your thoughts.
I really think this would benefit the multiload, making it actually benefitting users by grouping their 1 language calls.

**Comment by jamuhl** [comment]
the regular case in i18next is not to load 1 language - but a set: eg. having user language `en-US` will result in loading `en-US` (with translations different to `en`) and `en` plus an eventual fallback language.

The option is used rarely as it does not give you much benefit nowadays...loading multiple files in parallel is as fast.

You still get the one language call setting i18next to only load one (set fallbackLng: false and load: 'languageOnly'). Without this code changes that will work -> only difference your response always contains the language as most outer object member.

Not having this configuration set - your solution will do 2-3 requests depending on fallbackLng needed.

**Comment by fbarbare** [comment]
Ok, I did not know all that... 😄 

Anyway, in my case, we have about 5 namespaces per page, which would end up making between 5 and 20 requests based on the chosen and default language and the setup. And the number of calls will increase based on the number of namespaces.

Having this option of having API calls being grouped per language would make it drop to  1 to 4 calls maximum, no matter your setup. And make your API much easier to build than having the option of fetching multiple languages at the same time. It'd be like having the "middle" option for loading translations.

**Comment by jamuhl** [comment]
building the backend API for this is like 4 lines of code in node.js - express. https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L102

So honestly for me that "middle" option is not worth the additional complexity - we might add this in future as more devs request this - but i guess that won't happen (loading 20 static translations from eg. https://locize.com with pushed static files to edge locations is faster anytime with less memory pressure on your server).

Still you got the option to use this in a custom backend. You might even share that with the community. https://www.i18next.com/overview/plugins-and-utils#backend-extenders

**Comment by wheelo** [comment]
Is that possible to load languages using webpack import('lang/en')?

**Comment by wheelo** [comment]
@jamuhl

**Comment by jamuhl** [comment]
@wheelo https://www.i18next.com/how-to/add-or-load-translations

**Comment by wheelo** [comment]
So `addResourceBundle` under the hood uses the `dynamic import` to load resource?
@jamuhl

**Pull request closed without merging**
